global:
  scrape_interval: 19s

scrape_configs:
  - job_name: "prometheus_master"
    scrape_interval: 12s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'nginx_status'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']